// Generated by scripts/build-gallery.js - do not edit by hand.
window.GALLERY_DATA = {
  "action": [
    {
      "src": "assets/images/action/action-1.jpg"
    },
    {
      "src": "assets/images/action/action-2.jpg"
    },
    {
      "src": "assets/images/action/action-3.jpg"
    },
    {
      "src": "assets/images/action/action-4.jpg",
      "alt": "Shooter in a North Shore Custom Rifles shirt kneeling at a barricade"
    },
    {
      "src": "assets/images/action/action-5.jpg",
      "alt": "Shooting off a tire barricade at a match"
    },
    {
      "src": "assets/images/action/action-6.jpg",
      "alt": "Shooter behind a barricade with a brown chassis rifle and suppressor"
    },
    {
      "src": "assets/images/action/action-7.jpg",
      "alt": "Shooter behind a barricade with a teal chassis rifle and suppressor"
    }
  ],
  "builds": [
    {
      "src": "assets/images/builds/build-2.jpg"
    },
    {
      "src": "assets/images/builds/build-3.jpg"
    },
    {
      "src": "assets/images/builds/build-barreled-actions.jpg",
      "alt": "Barreled actions",
      "rotate": 180
    },
    {
      "src": "assets/images/builds/build-blue-chassis.jpg",
      "alt": "Blue chassis rifle with suppressor on a shooting rest"
    },
    {
      "src": "assets/images/builds/build-chassis.jpg"
    },
    {
      "src": "assets/images/builds/build-orange-chassis.jpg"
    }
  ],
  "machine": [
    {
      "src": "assets/images/machine/machine-1.jpg"
    },
    {
      "src": "assets/images/machine/machine-2.jpg"
    },
    {
      "src": "assets/images/machine/machine-3.jpg"
    },
    {
      "src": "assets/images/machine/machine-4.jpg"
    },
    {
      "src": "assets/images/machine/machine-5.jpg"
    },
    {
      "src": "assets/images/machine/machine-6.jpg"
    },
    {
      "src": "assets/images/machine/machine-7.jpg"
    },
    {
      "src": "assets/images/machine/machine-8.jpg"
    },
    {
      "src": "assets/images/machine/machine-9.jpg"
    },
    {
      "src": "assets/images/machine/machine-10.jpg"
    },
    {
      "src": "assets/images/machine/machine-11.jpg"
    },
    {
      "src": "assets/images/machine/machine-12.jpg"
    },
    {
      "src": "assets/images/machine/machine-13.jpg"
    },
    {
      "src": "assets/images/machine/machine-14.jpg"
    }
  ],
  "specialty": [
    {
      "src": "assets/images/specialty/specialty-1.jpg"
    },
    {
      "src": "assets/images/specialty/specialty-2.jpg"
    },
    {
      "src": "assets/images/specialty/specialty-3.jpg"
    },
    {
      "src": "assets/images/specialty/specialty-4.jpg"
    },
    {
      "src": "assets/images/specialty/specialty-5.jpg"
    },
    {
      "src": "assets/images/specialty/specialty-6.jpg"
    }
  ],
  "leaderboard": [
    {
      "src": "assets/images/leaderboard/alabama-precision-open-3rd.jpg",
      "alt": "Alabama Precision Open 3rd place trophy",
      "caption": "Alabama Precision Open · 3rd place"
    },
    {
      "src": "assets/images/leaderboard/altus-2025-long-range-3rd.jpg",
      "alt": "Competitor holding an Altus Long Range Classic Series 3rd place plaque",
      "caption": "Altus Long Range Classic Series · 3rd place"
    },
    {
      "src": "assets/images/leaderboard/altus-2026-long-range-challenge-3rd.jpg",
      "alt": "Blue chassis competition rifle with the Altus 2026 Long Range Challenge Series 3rd place plaque",
      "caption": "Altus 2026 Long Range Challenge Series · 3rd place"
    },
    {
      "src": "assets/images/leaderboard/lprc-2026-3rd-place.jpg",
      "alt": "Competitor holding the LPRC 2026 Bayou Rows Precision trophy",
      "caption": "Bayou Rows Precision · LPRC 2026 · 3rd place"
    },
    {
      "src": "assets/images/leaderboard/lprc-2026-podium.jpg",
      "alt": "Podium with the LPRC 2026 Finals 1st place trophy",
      "caption": "LPRC 2026 Finals · 1st place"
    },
    {
      "src": "assets/images/leaderboard/lprc-2026-trophy.jpg",
      "alt": "Bayou Rows Precision LPRC 2026 trophy in front of a competition rifle",
      "caption": "Bayou Rows Precision · LPRC 2026"
    },
    {
      "src": "assets/images/leaderboard/lprc-outlaw-match-1st.jpg",
      "alt": "Competitor with his blue chassis rifle and the LPRC Outlaw Match first place tumbler",
      "caption": "LPRC Outlaw Match · 1st place"
    }
  ]
};
