#!/usr/bin/env node
/**
 * Scans the photo folders under assets/images/ and writes js/gallery-data.js,
 * which the site uses to build its photo sections.
 *
 *   assets/images/action/       -> "Action shots"
 *   assets/images/builds/       -> "Completed builds"
 *   assets/images/machine/      -> "Machine work"
 *   assets/images/specialty/    -> "Specialty"
 *   assets/images/leaderboard/  -> "On the leaderboard"
 *
 * Drop photos in a folder, run `node scripts/build-gallery.js`, refresh the page.
 * (GitHub Actions also runs this on every deploy.)
 *
 * Optional: put a captions.json in a folder to add captions / alt text / rotation:
 *   { "photo.jpg": { "caption": "Shown in the big view", "alt": "Describes the photo", "rotate": 180 } }
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const imagesDir = path.join(root, "assets", "images");
const folders = ["action", "builds", "machine", "specialty", "leaderboard"];
const exts = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);
const bigBytes = 1024 * 1024;

const data = {};
for (const folder of folders) {
  const dir = path.join(imagesDir, folder);
  data[folder] = [];
  if (!fs.existsSync(dir)) continue;

  let meta = {};
  const metaFile = path.join(dir, "captions.json");
  if (fs.existsSync(metaFile)) {
    try { meta = JSON.parse(fs.readFileSync(metaFile, "utf8")); }
    catch (e) { console.warn(`! ${folder}/captions.json is not valid JSON: ${e.message}`); }
  }

  for (const name of fs.readdirSync(dir).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))) {
    const ext = path.extname(name).toLowerCase();
    if (name === "captions.json") continue;
    if (!exts.has(ext)) { console.warn(`! skipped ${folder}/${name} (browsers can't show ${ext || "this file"}; convert to .jpg)`); continue; }
    const size = fs.statSync(path.join(dir, name)).size;
    if (size > bigBytes) console.warn(`! ${folder}/${name} is ${(size / bigBytes).toFixed(1)} MB - resize to ~1600px wide for a faster site`);
    const m = meta[name] || {};
    const item = { src: `assets/images/${folder}/${encodeURIComponent(name)}` };
    if (m.alt) item.alt = m.alt;
    if (m.caption) item.caption = m.caption;
    if (m.rotate) item.rotate = m.rotate;
    data[folder].push(item);
  }
  console.log(`${folder}: ${data[folder].length} photo(s)`);
}

const out = "// Generated by scripts/build-gallery.js - do not edit by hand.\nwindow.GALLERY_DATA = " + JSON.stringify(data, null, 2) + ";\n";
fs.writeFileSync(path.join(root, "js", "gallery-data.js"), out);
console.log("wrote js/gallery-data.js");
